insert into menu(id,name,description,category,imgurl,price) values (1,'Beef Brocoli','A description of a Beef Brocoli.','chinese','assets/img/chinese_beefbrocoli.jpeg',7.99);
insert into menu(id,name,description,category,imgurl,price) values (10,'Juice','A description of Juice.','chinese','assets/img/',11.79);
insert into menu(id,name,description,category,imgurl,price) values (11,'Soup','A description of Soup.','chinese','assets/img/',12.89);
insert into menu(id,name,description,category,imgurl,price) values (12,'Almonds','A description of Almonds.','chinese','assets/img/',17.69);
insert into menu(id,name,description,category,imgurl,price) values (2,'Broccoli','A description of Broccoli.','chinese','assets/img/chinese_dumpling.jpeg',14.99);
insert into menu(id,name,description,category,imgurl,price) values (3,'Eggplant','A description of Eggplant.','chinese','assets/img/chinese_eggroll.jpeg',12.99);
insert into menu(id,name,description,category,imgurl,price) values (4,'Onion','A description of an Onion.','chinese','assets/img/chinese_lomein.jpeg',10.49);
insert into menu(id,name,description,category,imgurl,price) values (5,'Milk','A description of Milk.','chinese','assets/img/chinese_spicybrocoli.jpeg',14.49);
insert into menu(id,name,description,category,imgurl,price) values (6,'Steak','A description of Steak.','chinese','assets/img/',11.19);
insert into menu(id,name,description,category,imgurl,price) values (7,'Chicken','A description of Chicken.','chinese','assets/img/',14.49);
insert into menu(id,name,description,category,imgurl,price) values (8,'Eggs','A description of Eggs.','chinese','assets/img/',12.49);
insert into menu(id,name,description,category,imgurl,price) values (9,'Cheese','A description of Cheese.','chinese','assets/img/',12.99);

insert into user(id,name,address,username,password,adminstatus) values (1,'Sam Parsons','123 Address, Washington, DC, 20010','sam','pw',true);
insert into user(id,name,address,username,password,adminstatus) values (10,'David Parsons','123 Road, Bloomington, DC, 20010','emi','pw',false);
insert into user(id,name,address,username,password,adminstatus) values (11,'Sharon Parsons','123 Road, Bloomington, DC, 20010','emi','pw',false);
insert into user(id,name,address,username,password,adminstatus) values (12,'Aurora Alvarez','123 Calle, Buenos Aries, BS, 20010','suegra','pw',false);
insert into user(id,name,address,username,password,adminstatus) values (13,'Diego Candia','123 Calle, Viedma, RN, 20010','suegro','pw',false);
insert into user(id,name,address,username,password,adminstatus) values (14,'Jorge Alvarez','123 Calle, Buenos Aries, BS, 20010','tio','pw',false);
insert into user(id,name,address,username,password,adminstatus) values (2,'Georgi Candia','123 Street, Washington, DC, 20010','georgi','pw',true);
insert into user(id,name,address,username,password,adminstatus) values (3,'Puck Parsons','123 Road, Washington, DC, 20010','puck','pw',false);
insert into user(id,name,address,username,password,adminstatus) values (4,'Ben Parsons','123 Road, Washington, DC, 20010','ben','pw',false);
insert into user(id,name,address,username,password,adminstatus) values (5,'Marabai Beczkiewicz','123 Road, Bloomington, IN, 47408','merbs','pw',false);
insert into user(id,name,address,username,password,adminstatus) values (6,'Milo Beczkiewicz','123 Road, Bloomington, DC, 20010','milo','pw',false);
insert into user(id,name,address,username,password,adminstatus) values (7,'Annika Beczkiewicz','123 Road, Bloomington, DC, 20010','anni','pw',false);
insert into user(id,name,address,username,password,adminstatus) values (8,'Jana Parsons','123 Road, La Crosse, DC, 20010','jana','pw',false);
insert into user(id,name,address,username,password,adminstatus) values (9,'Logan Parsons','123 Road, La Crosse, DC, 20010','logie','pw',false);